version: "3.8"

services:
  glados:
    image: ghcr.io/comfuture/glados:latest
    restart: always
    environment:
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - SLACK_SIGNING_SECRET=${SLACK_SIGNING_SECRET}
      - SLACK_APP_TOKEN=${SLACK_APP_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=gpt-4-turbo-preview
      - GLADOS_ASSISTANT_ID=asst_eDdt0BM0z4iIcdBPdXJ3H3ZK
      - MONGODB_URI=${MONGODB_URI}
      - CLOUDFLARE_ACCOUNT_ID=${CLOUDFLARE_ACCOUNT_ID}
      - CLOUDFLARE_ACCESS_KEY_ID=${CLOUDFLARE_ACCESS_KEY_ID}
      - CLOUDFLARE_SECRET_ACCESS_KEY=${CLOUDFLARE_SECRET_ACCESS_KEY}
      - PUBLIC_R2_BUCKET_URL=${PUBLIC_R2_BUCKET_URL}
