apiVersion: v1
kind: Secret
metadata:
  name: ipny-bot
type: Opaque
stringData:
  SLACK_BOT_TOKEN: $SLACK_BOT_TOKEN
  SLACK_SIGNING_SECRET: $SLACK_SIGNING_SECRET
  SLACK_APP_TOKEN: $SLACK_APP_TOKEN
  OPENAI_API_KEY: $OPENAI_API_KEY
  OPENAI_MODEL: gpt-4
  OPENAI_MAX_TOKEN: '8192'
