on:
  push:
    branches:
    - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SLACK_APP_TOKEN: ${{ secrets.SLACK_APP_TOKEN }}
      SLACK_SIGNING_SECRET: ${{ secrets.SLACK_SIGNING_SECRET }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
    - uses: actions/checkout@v3
    - uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}
    - name: make env file
      run: |
        echo SLACK_BOT_TOKEN=$SLACK_BOT_TOKEN >> .env
        echo SLACK_APP_TOKEN=$SLACK_APP_TOKEN >> .env
        echo SLACK_SIGNING_SECRET=$SLACK_SIGNING_SECRET >> .env
        echo OPENAI_API_KEY=$OPENAI_API_KEY >> .env
    - name: send files to server
      run: |
        sh -c "rsync -avzO --delete --exclude=__pycache__ --exclude=node_modules \
           -e 'ssh -o StrictHostKeyChecking=no' . ubuntu@glados.changkyun.kim:service/glados"
    - name: install dependencies
      run: |
        ssh -o StrictHostKeyChecking=no -A -tt ubuntu@glados.changkyun.kim 'bash -l -c ". ~/.nvm/nvm.sh && cd service/glados && yarn"'
    - name: restart service
      run: |
        ssh -o StrictHostKeyChecking=no -A -tt ubuntu@glados.changkyun.kim 'bash -l -c "sudo systemctl restart glados.service"'
