on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SLACK_APP_TOKEN: ${{ secrets.SLACK_APP_TOKEN }}
      SLACK_SIGNING_SECRET: ${{ secrets.SLACK_SIGNING_SECRET }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      OPENAI_MODEL: ${{ secrets.OPENAI_MODEL }}
    steps:
      - uses: actions/checkout@v4
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - name: create remote docker context
        run: docker context create remote --docker "host=${{ secrets.DOCKER_HOST }}"
      - name: login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build and push
        uses: docker/build-push-action@v5.2.0
        with:
          tags: ghcr.io/$GITHUB_REPOSITORY:$GITHUB_SHA
          context: .
          file: ./Dockerfile
          push: true
      - name: deploy to remote
        run: |
          echo $GITHUB_TOKEN | docker --context remote login ghcr.io -u $GITHUB_ACTOR --password-stdin
          docker --context remote pull ghcr.io/$GITHUB_REPOSITORY:$GITHUB_SHA
          docker --context remote compose up -d --force-recreate
