on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SLACK_APP_TOKEN: ${{ secrets.SLACK_APP_TOKEN }}
      SLACK_SIGNING_SECRET: ${{ secrets.SLACK_SIGNING_SECRET }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      OPENAI_MODEL: ${{ secrets.OPENAI_MODEL }}
    steps:
      - uses: actions/checkout@v4
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - name: create remote docker context
        run: docker context create remote ‐‐docker "host=${{ secrets.DOCKER_HOST }}"
      - name: login to gchr.io
        run: echo $GITHUB_TOKEN | docker login ghcr.io -u $GITHUB_USERNAME --password-stdin
      - name: build and push
        run: |
          docker build -t ghcr.io/$GITHUB_REPOSITORY:$GITHUB_SHA .
          docker push ghcr.io/$GITHUB_REPOSITORY:$GITHUB_SHA
      - name: deploy to remote
        run: docker --context remote compose up -d --force-recreate
