on:
  workflow_dispatch:

jobs:
  stop_container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: create remote context
        uses: arwynfr/actions-docker-context@v2
        with:
          docker_host: ${{ secrets.DOCKER_HOST }}
          context_name: remote
          ssh_key: ${{ secrets.SSH_KEY }}
      - name: skip strict host key checking
        run: |
          echo "Host *" >> ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config
      - name: stop container
        run: docker --context remote compose down
