name: manage
on:
  workflow_dispatch:
    inputs:
      action:
        description: "Action to perform"
        required: true
        default: start
        type: choice
        options:
          - start
          - stop

jobs:
  stop_container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: create remote context
        uses: arwynfr/actions-docker-context@v2
        with:
          docker_host: ${{ secrets.DOCKER_HOST }}
          context_name: remote
          ssh_key: ${{ secrets.SSH_KEY }}
      - name: skip strict host key checking
        run: |
          echo "Host *" >> ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config
      - name: start container
        if: ${{ github.event.inputs.action == 'start' }}
        run: docker --context remote compose up -d
      - name: stop container
        if: ${{ github.event.inputs.action == 'stop' }}
        run: docker --context remote compose down
