name: manage
on:
  workflow_dispatch:
    inputs:
      action:
        description: "Action to perform"
        required: true
        default: start
        type: choice
        options:
          - start
          - stop

jobs:
  manage_container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: create remote context
        uses: arwynfr/actions-docker-context@v2
        with:
          docker_host: ${{ secrets.DOCKER_HOST }}
          context_name: remote
          ssh_key: ${{ secrets.SSH_KEY }}
      - name: skip strict host key checking
        run: |
          echo "Host *" >> ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config
      - name: start container
        if: ${{ github.event.inputs.action == 'start' }}
        run: docker --context remote compose up -d
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_APP_TOKEN: ${{ secrets.SLACK_APP_TOKEN }}
          SLACK_SIGNING_SECRET: ${{ secrets.SLACK_SIGNING_SECRET }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL: ${{ secrets.OPENAI_MODEL }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_ACCESS_KEY_ID: ${{ secrets.CLOUDFLARE_ACCESS_KEY_ID }}
          CLOUDFLARE_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_SECRET_ACCESS_KEY }}
          PUBLIC_R2_BUCKET_URL: ${{ secrets.PUBLIC_R2_BUCKET_URL }}
      - name: stop container
        if: ${{ github.event.inputs.action == 'stop' }}
        run: docker --context remote compose down
